mediguest_reports/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('mediguest_reports.views',
    url(r'^client/(\d+)/pack$', 'client_pack', name="client_pack"),
    url(r'^client/(\d+)/pack_dynonly$', 'client_pack_dynonly', name="client_pack_dynonly"),
    url(r'^reports/validity/$', 'validity_report', name="validity_report"),
    url(r'^reports/service_charge_control_sheet/(?P<year>\d+)/(?P<week_num>\d+)/$', 'service_charge_control_sheet', name="service_charge_control_sheet"),
    url(r'^reports/service_charge_control_sheet_csv/(?P<year>\d+)/(?P<week_num>\d+)/$', 'service_charge_control_sheet_csv', name="service_charge_control_sheet_csv"),
    url(r'^service_charge_week/(?P<year>\d+)/$',    'service_charge_week',    name='service_charge_week'),
    url(r'^service_charge_payment_receipt/(?P<payment_id>\d+)/$',    'service_charge_payment_receipt',    name='service_charge_payment_receipt'),
)

third-party/xhtml2pdf/demo/djangoproject/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'djangoproject.views.index'),
    (r'^download', 'djangoproject.views.download'),
    (r'^ezpdf_sample', 'djangoproject.views.ezpdf_sample'),
    
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from settings import MEDIA_ROOT, STATIC_ROOT

from mediguest_admin.site import mediguest_admin_site
from django.contrib import admin
admin.site = mediguest_admin_site
admin.autodiscover()

urlpatterns = patterns('',
    # third-party stuff
    url(r'^foreignkeysearch/', include('foreignkeysearch.urls')),

    # static/uploaded files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': MEDIA_ROOT
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': STATIC_ROOT
    }),

    # custom stuff
    url(r'^mediguest_client_reports/',    include('mediguest_reports.urls')),
    url(r'^$',                     'mediguest_admin.views.front_page', name="frontpage"),

    # admin
    url(r'^admin/doc/',             include('django.contrib.admindocs.urls')),
    url(r'^admin/',                 include(mediguest_admin_site.urls)),
)

booking/models.py
from django.db import models
from clients.models import Client
from django.contrib.auth.models import User
from datetime import datetime
from decimal import Decimal
from keywork.mod.keyworker import Keyworker

class RoomType(models.Model):
    class Meta:
        ordering = ('name',)

    code = models.CharField(max_length=1, help_text="Single-letter code for this type of room.  For example, crash beds might use C or B, storage rooms: S, etc. Consult organisation policy.")
    name = models.CharField(max_length=255, help_text="Name of this room type")
    daily_rate = models.DecimalField(max_digits=10, decimal_places=5, default=Decimal("0.00"), help_text="Daily charge for this room type")
    is_client_room = models.BooleanField(default=False, help_text="Whether this room can be used by clients.  For example, storage rooms and offices cannot.")

    def plural_name(self):
        return self.name + u"s"

    def first_rooms_inline(self):
        first_rooms = self.room_set.all()[:3]
        first_room_names = [ unicode(r) for r in first_rooms ]
        first_rooms_inline_str = u", ".join(first_room_names)
        return first_rooms_inline_str

    def last_room(self):
        # FIXME: django doesn't support negative indexing on querysets, so this is the inefficient way.  Find another.
        tmp_list = list(self.room_set.all())
        return unicode(tmp_list[-1:][0])

    def as_example(self):
        return self.first_rooms_inline() + u"..." + self.last_room()

    def __unicode__(self):
        return self.name + " (" + self.code + ")"

class Room(models.Model):
    class Meta:
        ordering = ('type', 'number')

    type = models.ForeignKey(RoomType, help_text="Choose the which type of room this is.")
    number = models.IntegerField(help_text="Room number")
    keyworker = models.ForeignKey(Keyworker, help_text="Keyworker assigned to this room.  NOTE: For changes specific to one client, override in the client's details.")

    def __unicode__(self):
        return self.type.code + unicode(self.number)

class Booking(models.Model):
    class Meta:
        get_latest_by = 'start_date'

    client = models.ForeignKey(Client, help_text="Client who was/is booked in.")
    made_by = models.ForeignKey(User, help_text="Which staff member made, or is making, the booking")
    room_choice_filter = {
        'type__is_client_room': True,
    }
    room = models.ForeignKey(Room, limit_choices_to=room_choice_filter, help_text="Which room the client is booked into")

    rules_read = models.NullBooleanField(help_text="Have the rules (from the client pack) been read to this client?")

    start_date = models.DateTimeField(default=datetime.now, help_text="When the booking began")
    end_date = models.DateTimeField(blank=True, null=True, help_text="When the booking ended.  Leave blank if still resident.")

    reason_for_leaving = models.TextField(blank=True, null=True, help_text="Why the client booked out.  Leave blank if still resident.")

    def days_stayed(self):
        if self.end_date:
            date_diff = self.end_date - self.start_date
        else:
            date_diff = datetime.now() - self.start_date
        num_days = date_diff.days
        return num_days

    def total_payable(self):
        # FIXME: what IS this?!
        #        should probably generate it from a foreignkey on ServiceCharge
        #        to Booking.  -- ServiceCharges accrued during a given stay, in
        #        other words.
        num_days = self.days_stayed()
        amt = self.room.type.daily_rate * num_days
        return amt

    def __unicode__(self):
        desc = unicode(self.client) + " booked into " + unicode(self.room) + " from " + unicode(self.start_date)
        if (self.end_date):
            desc += " to " + unicode(self.end_date)
        else:
            desc += " (ongoing)"
        return desc

mediguest_reports/models.py
from django.db import models

mediguest_reports/views.py
from django import http
import cgi
from booking.models import RoomType
from drug_db.models import Drug
from html_to_pdf import PISA_PDFRenderer as PDFRenderer
from django.shortcuts import get_object_or_404, render
from datetime import datetime, timedelta
from servicecharges.models import ServiceChargePayment
from django.template import Template, Context, loader

def _day_iter(start_date, end_date, step=1):
    dt = start_date
    counter = 1
    while dt <= end_date:
        yield dt, counter
        counter += 1
        dt += timedelta(days=step)

def _iso_week_start(dt):
    year, weeknum, weekday = dt.isocalendar()
    if year != dt.year:
        # this year starts mid-week, so we need to account for the year before
        starting_month = 12
        starting_day = (dt - timedelta(days=weekday-1)).day
    else:
        starting_month = 1
        starting_day = 1

    year_start = datetime(year, starting_month, starting_day)

    return year_start

def _week_start_end(year, week_num):
    year_start = datetime(year, 1, 1)
    iso_year_start = _iso_week_start(year_start)

    week_start = iso_year_start + timedelta(weeks=week_num-1)
    week_end = week_start + timedelta(days=6, hours=23, minutes=59)

    return week_start, week_end

def pdf_report(req, tpl, extra_args={}):
    from clients.models import Client

    br = "<br>"

    report_title = "Client Pack"
    org_name = "Your Organisation"

    street1 = "1 YourOrg Street"
    town = "YourTown"
    postcode = "P057 C0D3"

    phone = "+44 2342 3435"
    fax = "+44 2324 2235"

    addr_html = br.join(street1, town, post_code)
    addr_inline = ", ".join(street1, town, post_code)

    pdf_renderer = PDFRenderer()

    args = {
        'pagesize':             "A4",

        'title':                report_title,
        'org_name':             org_name,
        'org_address_html':     addr_html,
        'org_address_inline':   addr_inline,
        'org_phone':            phone,
        'org_fax':              fax,
        'parent_org':           parent_org,
        'is_print':             True,
    }
    args.update(extra_args)

    pdf_buf = pdf_renderer(req, tpl, args)

    return http.HttpResponse(
        pdf_buf,
        mimetype='application/pdf'
    )

def client_report(request, report_fname, client_id, extra_args={}):
    from clients.models import Client

    client = get_object_or_404(Client, pk=client_id)
    deposit = 10.00

    my_args = {
        'deposit':              deposit,
        'client':               client,
        'room_types':           RoomType.objects.all().filter(is_client_room=True),
    }
    my_args.update(extra_args)

    return pdf_report(request, report_fname, extra_args=my_args)

def client_pack(request, client_id):
    report_fname = 'mediguest_reports/client_pack/client_pack.html'
    return client_report(request, report_fname, client_id)

def client_pack_dynonly(request, client_id):
    extra_args = { 'page_offset': '13' }
    report_fname = 'mediguest_reports/client_pack_dynonly.html'
    return client_report(request, report_fname, client_id, extra_args=extra_args)

def validity_report(request):
    from validity_checks import DoseValidityCheck
    from django.template.loader import get_template
    from django.template import RequestContext

    template_src = "mediguest_reports/validity_report.html";
    template = get_template(template_src)

    validity_checks = [ DoseValidityCheck ]
    validity_results = []
    for chk in validity_checks:
        inst = chk()
        res = inst()
        validity_results.append(res)

    args = {
        'validity_results':  validity_results,
    }

    context = RequestContext(request, args)
    html  = template.render(context)

    return http.HttpResponse(html)

def service_charge_control_sheet(request, year, week_num):
    from servicecharges.models import ServiceCharge

    template = "mediguest_reports/service_charge_control_sheet.html"
    start, end = _week_start_end(int(year), int(week_num))

    service_charges = ServiceCharge.objects.filter(date_charged__range=(start, end), type__include_on_control_sheet=True)

    args = {
        'year':             year,
        'week_num':         week_num,
        'service_charges':  service_charges,
        'start':            start,
        'end':              end,
    }

    return pdf_report(request, template, extra_args=args)

def csv_report(req, tpl, extra_args={}):
    t = loader.get_template(tpl)

    args = {}
    args.update(extra_args)

    context = Context(args)
    csv_buf = t.render(context)

    return http.HttpResponse(
        csv_buf,
        mimetype='text/csv'
    )

def service_charge_control_sheet_csv(request, year, week_num):
    from servicecharges.models import ServiceCharge

    template = "mediguest_reports/service_charge_control_sheet.csv"
    start, end = _week_start_end(int(year), int(week_num))

    service_charges = ServiceCharge.objects.filter(date_charged__range=(start, end), type__include_on_control_sheet=True)

    args = {
        'year':             year,
        'week_num':         week_num,
        'service_charges':  service_charges,
        'start':            start,
        'end':              end,
    }

    return csv_report(request, template, extra_args=args)

def service_charge_week(req, year):
    tpl = "mediguest_reports/service_charge_week.html"

    weeks = {}
    jan_1st = datetime(int(year), 1, 1)
    year_start = _iso_week_start(jan_1st)
    year_end = year_start+timedelta(days=365, minutes=-1)
    for start, week_num in _day_iter(year_start, year_end, step=7):
        end = start + timedelta(days=6, hours=23, minutes=59, seconds=59)
        weeks[week_num] = { 'start': start, 'end': end }

    args = {
        'year':         year,
        'weeks':        weeks,
    }

    return render(req, tpl, args)

def service_charge_payment_receipt(req, payment_id):
    tpl = "mediguest_reports/service_charge_payment_receipt.html"

    payment = get_object_or_404(ServiceChargePayment, id=payment_id)
    extra_args = {
        'payment':              payment,
    }

    return pdf_report(req, tpl, extra_args=extra_args)

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/B1 - Licence Agreement - Part B.html
<div class="document">
    <h2>Guest Agreement</h2>

    <table>
	    <tr>
		    <th>Name of guest</th>
		    <td colspan="2">{{ client }}</td>
	    </tr>
    </table>

    <h3>First Admission</h3>

    {% if client.first_admission_date %}
        <table>
            <tr>
                <th>Date of First Admission</th>
                <td>
                    {{ client.first_admission_date|date:"Y/M/d" }}
                </td>

                <th>Staff member responsible for initial booking-in</th>
                <td>
                    {% if client.first_booked_in_by.first_name or client.first_booked_in_by.last_name %}
                        {{ client.first_booked_in_by.first_name }}
                        {{ client.first_booked_in_by.last_name }}
                    {% else %}
                        {{ client.first_booked_in_by.username }}
                    {% endif %}
                </td>
            </tr>
        </table>
    {% else %}
        (none yet)
    {% endif %}

    <h3>Subsequent Admissions</h3>

    <table class="admissions">
        <tr>
            <th>B.I.D.</th>
            <th>Room</th>
            <th>Sched. 3 Read</th>
            <th>Sched. 4 Read</th>
            <th>Total Payable</th>
            <th>B.O.D.</th>
        </tr>
        {% for booking in client.subsequent_admissions %}
            <tr>
                <td>{{ booking.start_date|date:"Y/M/d" }}</td>
                <td>{{ booking.room }}</td>
                <td>{{ booking.sched_3_read|yesno:"Y,N," }}</td>
                <td>{{ booking.sched_4_read|yesno:"Y,N," }}</td>
                <td>&pound;{{ booking.total_payable|floatformat:2 }}{% ifequal booking.end_date Null %} (ongoing){% endifequal %}</td>
                <td>{% if booking.end_date %}{{ booking.end_date|date:"Y/M/d" }}{% else %}(ongoing){% endif %}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="8" style="text-align: center">(none yet)</td>
            </tr>
        {% endfor %}
    </table>

    <h3>Notes</h3>

    <ul>
        <li>Current daily service charges are:

            <table>
            	{% for r in room_types %}
            		<tr>
            			<th>{{ r.name }}</th>
            			<td>&pound;{{ r.daily_rate|floatformat:2 }}</td>
            		</tr>
            	{% endfor %}
            </table>
        </li>

        <li>Staff must ensure that Sections ... the <em>License Agreement</em> have been read to, and agreed by, the guest being booked in.</li>
    </ul>
</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/B2 - Room Inventory.html
<div class="document">
    <h2>Room Inventory</h2>

    <table class="bordered">
        <tr>
            <td>Item</td>
     	    <td>Condition**</td>
        	    <td>Fault</td>
        	    <td>Comments</td>
    	</tr>

		{% for item in client.room.inventoryitem_set.all %}
       	<tr>
			<td>{{ item.identifier }}</td>
           	<td>{{ item.condition }}</td>
           	<td>{{ item.fault }}</td>
           	<td>{{ item.comments }}</td>
       	</tr>
        {% endfor %}
    </table>
</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/C - Front of File.html
<div class="document">

<h2>Front of File Details</h2>

<table class="bordered">
    <tr>
        <th>Guest Name</th>
        <td>{{ client }}</td>
    </tr>
    <tr>
        <th>Date of Birth</th>
        <td>{{ client.date_of_birth|date:"Y/M/d" }}</td>
    </tr>
    <tr>
        <th>NI Number</th>
        <td>{{ client.national_insurance_no }}</td>
    </tr>
    <tr>
        <th>Booking-in Date</th>
        <td>
            {% if client.room %}
                {{ client.booking_set.latest.start_date|date:"Y/M/d" }}
            {% else %}
                (no room yet)
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Keyworker</th>
        <td>{{ client.keyworker }}</td>
    </tr>
    <tr>
        <th>Booking-out Date</th>
        <td>
            {% if client.room %}
                {{ client.room.end_date }}
            {% else %}
                n/a
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Reason for leaving</th>
        <td>
            {% if client.room %}
                {{ client.room.reason_for_leaving }}
            {% else %}
                n/a
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Service Charge Arrears</th>
        <td>&pound;{{ client.service_charge_arrears|floatformat:2 }}</td>
    </tr>
</table>

</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/D - Emergency Sheet.html
{% load thumbnail %}
<div class="document">

<div style="font-size: 18pt; font-weight: bold">{{org_name}}/div>

<h2>Emergency Information Sheet</h2>

<p>Give this sheet to the vehicle medical crew, when a guest is taken from {{ org_name }}.</p>

<table class="bordered">
    <tr>
        <th>Name</th>
        <td>{{ client }}</td>
{% if client.photo %}<td rowspan="7" class="emergency-sheet-photo">
            <img
                class="emergency-sheet-photo"
                title="Emergency Sheet Photo"
                src="{% thumbnail client.photo 200x200 %}"
                alt=""
            />
        </td>
{% endif %}
    </tr>
    <tr><th>Date of Birth</th>      <td>{{ client.date_of_birth|date:"Y/M/d" }}</td></tr>

    <tr><th>G.P. Name</th>          <td>{{ client.gp }}</td></tr>
    <tr><th>G.P. Address</th>       <td>{{ client.gp.address.address_inline }}</td></tr>
    <tr><th>G.P. Telephone</th>     <td>{{ client.gp.phone }}</td></tr>
    <tr><th>G.P. Mobile</th>        <td>{{ client.gp.mobile }}</td></tr>

    <tr>
        <th>
            Religion<br>
            <span class="legalese">(for contact in emergencies)</span>
        </th>
        <td>{{ client.religion }}</td>
    </tr>
</table>


<h3>Current Medication(s)</h3>

<table class="bordered">
    <tr>
        <th>Medication</th>
        <th>Dosage</th>
        <th>How often</th>
        <th>What for</th>
        <th>Time using</th>
    </tr>

    {% for med in client.current_medications %}
        <tr>
            <td>{{ med.drug.name }}</td>
            <td>{{ med.dose }} {{ med.drug.units }}</td>
            <td>{{ med.frequency }}</td>
            <td>{{ med.purpose }}</td>
            <td>{{ med.using_time_as_str }}</td>
        </tr>
    {% endfor %}
</table>


<h3>Medical problems</h3>

{{ client.medical_problems }}


<h3>Mobility problems</h3>

{{ client.mobility_problems }}


<h3 class="further-info">For further information contact:</h3>

<p>{{ org_name }}, {{ org_address_inline }}, {{ org_phone }}</p>

</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/E - Information Card.html
<div class="document information-card">
	<h2>Information Card</h2>

	<table class="bordered information-card">
	    <tr>
            <th>Surname(s)</th>
            <td colspan="2">{{ client.surnames }}</td>
        </tr>
	    <tr>
            <th>Forename(s)</th>
            <td colspan="2">{{ client.forenames }}</td>
        </tr>
	    <tr>
            <th>Date of Birth</th>
            <td colspan="2">{{ client.date_of_birth|date:"Y/M/d" }}</td>
        </tr>
	    <tr>
            <th>National Insurance No.</th>
            <td colspan="2">{{ client.national_insurance_no }}</td>
        </tr>

	    <tr>
            <th>Room No.</th>
            <td colspan="2">
                {% if client.room %}
                    {{ client.booking_set.latest.start_date }}
                {% else %}
                    (no current bookings)
                {% endif %}
            </td>
        </tr>
	    <tr>
            <th>Date moved in</th>
            <td colspan="2">{{ client.room.start_date|date:"Y/M/d" }}</td>
        </tr>
	    <tr>
            <th>Date moved out</th>
            <td colspan="2">
                {% if client.room %}
                    {{ client.booking_set.latest.end_date|date:"Y/M/d" }}
                {% else %}
                    (continued resident)
                {% endif %}
            </td>
        </tr>
	    <tr>
            <th>Keyworker</th>
            <td colspan="2">{{ client.keyworker }}</td>
        </tr>

	    <tr>
	    	<th>Contact NOK in Emergency?</th>
	    	<td colspan="2">
	    		{% ifnotequal client.contact_next_of_kin Null %}
	    			{% if client.contact_next_of_kin %}
		    			Yes
		    		{% else %}
		    			No
		    		{% endif %}
		    	{% else %}
		    		(unknown)
		    	{% endifnotequal %}
		    </td>
		</tr>

	    <tr>
	        <th>Contact with other agencies / organisations</th>
	        <td colspan="2">
	            <table class="subtable">
                    <tr>
                        <th>Agency</th>
                        <th>Contact Person</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Current?</th>
                    </tr>
                    {% for ac in client.agencycontact_set.all %}
                        <tr>
                            <td>{{ ac.agency_rep.organization }}</td>
                            <td>{{ ac.agency_rep.member }}</td>
                            <td>{{ ac.agency_rep.organization.address.address_inline }}</td>
                            <td>{{ ac.agency_rep.member.mobile_phone_no }}</td>
                            <td>
                                {% if ac.follow_up_required %}
                                    Y
                                {% else %}
                                    N
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">
                                (no agency contacts yet)
                            </td>
                        </tr>
                    {% endfor %}
	            </table>
	        </td>
	    </tr>

	    <tr>
	    	<th>Presented as Homeless?</th>
	    	<td colspan="2">
	    		{% ifnotequal client.presented_as_homeless Null %}
		    		{% if client.presented_as_homeless %}
		    			Yes
		    		{% else %}
		    			No
		    		{% endif %}
		    	{% else %}
		    		(unknown)
		    	{% endifnotequal %}
	    	</td>
	    </tr>

	    <tr>
	        <th>Health History</th>
	        <td colspan="2">
	            <table>
	                <tr>
	                    <th colspan="4">Hospital Admissions</th>
	                </tr>
                    <tr>
                            <th>Admission date</th>
                            <th>Hospital</th>
		                    <th>Reason</th>
		                    <th>Length of Stay</th>
                    </tr>
	                {% for adm in client.hospitaladmission_set.all %}
		                <tr>
                            <td>{{ adm.admission_date|date:"Y/M/d" }}</td>
                            <td>{{ adm.hospital.name }}</td>
		                    <td>{{ adm.reason }}</td>
		                    <td>
		                    	{% if adm.checkout_date %}
			                    	{{ adm.pretty_duration }}
		                    	{% else %}
		                    		(ongoing)
		                    	{% endif %}
		                    </td>
		                </tr>
		            {% endfor %}
	            </table>
	        </td>
	    </tr>

	    <tr>
	        <th>Current Medical Problems</th>
	        <td colspan="2">
                {% if client.medical_problems %}
                    {{ client.medical_problems }}
                {% else %}
                    n/a
                {% endif %}
            </td>
	    </tr>

	    <tr>
	        <th>Mobility Problems</th>
	        <td colspan="2">
                {% if client.mobility_problems %}
                    {{ client.mobility_problems }}
                {% else %}
                    n/a
                {% endif %}
            </td>
	    </tr>

	    <tr>
	        <th>Prescribed Medication</th>
	        <td colspan="2">
	            <table>
	                <tr>
	                    <th>Medication</th>
	                    <th>Dosage</th>
	                    <th>Frequency</th>
	                    <th>What for</th>
	                    <th>Time using</th>
	                </tr>
                    {% for med in client.current_medications %}
                        <tr>
                            <td>{{ med.drug.name }}</td>
                            <td>{{ med.dose }} {{ med.drug.units }}</td>
                            <td>{{ med.frequency }}</td>
                            <td>{{ med.purpose }}</td>
                            <td>{{ med.using_time_as_str }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">
                                (no current medications on record)
                            </td>
                        </tr>
                    {% endfor %}
	            </table>
	        </td>
	    </tr>

	    <tr>
	    	<th>Registered Disabled?</th>
	    	<td colspan="2">{% if client.disabled_reg_no %}Yes{% else %}No{% endif %}</td>
	    </tr>
        <tr>
            <th>Disabled Number</th>
            <td colspan="2">{{ client.disabled_reg_no }}</td>
        </tr>

	    <tr>
	    	<th>Assistance/Support Required</th>
	    	<td colspan="2">{{ client.assistance_required }}</td>
	    </tr>
	</table>
</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/G - Booking In Form.html
<div class="document">

<h2>Booking-in Form</h2>

<p>
{{ org_name }}<br>
{{ org_address_inline }}
</p>

<table class="bordered">
    <tr>
        <th>Surname</th>
        <th>Forename(s)</th>
        <th>D.O.B.</th>
        <th>National Insurance No.</th>
    </tr>
    <tr>
        <td>{{ client.surnames }}</td>
        <td>{{ client.forenames }}</td>
        <td>{{ client.date_of_birth|date:"Y/M/d" }}</td>
        <td>{{ client.national_insurance_no }}</td>
    </tr>

    <tr>
        <th>Mobile Phone No.</th>
        <th>Booking-in Date</th>
        <th>Keyworker</th>
        <th>Ref. Number</th>
    </tr>

    <tr>
        <td>{{ client.mobile_phone_no }}</td>
        <td>
            {% if client.room %}
                {{ client.booking_set.latest.start_date|date:"Y/M/d" }}
            {% else %}
                (no room yet)
            {% endif %}
        </td>
        <td>{{ client.keyworker }}</td>
        <td>{{ client.reference_no }}</td>
    </tr>
</table>

<h3>Accomodation Allocated</h3>

{% if client.room %}
    <p>{{ client.room.type }}</p>
{% else %}
    (no booking yet)
{% endif %}
</table>

<h3>Completing Booking-in</h3>

<table>
    <tr>
        <th>Signed</th>
        <th>Date</th>
    </tr>
    <tr>
        <td class="signature_box">&nbsp;</td>
        <td class="signature_box">&nbsp;</td>
        <td class="signature_box">&nbsp;</td>
    </tr>
</table>

<p>This is to confirm that the above licensee is a guest at {{ org_name }}</p>

</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/J - Key Receipt Form.html
<div class="document">

<h2>Key Receipt Form</h2>

<table>
    <tr>
        <th>Guest Name</th>
        <td>{{ client }}</td>
    </tr>
    <tr>
        <th>Room Number</th>
        <td>{{ client.room }}</td>
    </tr>
    <tr>
        <th>Licence Start Date</th>
        <td>{{ client.latest_booking.start_date|date:"Y/M/d" }}</td>
    </tr>
</table>

<p>&nbsp;</p>

<ul class="checkboxes">
	<li>I have paid my deposit of &pound;{{ deposit|floatformat:2 }} which
	will be reimbursed on return of my key at the end of my licence</li>

	<li>I agree that I will pay for any replacements should my key be
	mislaid</li>

	<li>I will return all keys to {{ org_name }} when my licence has
	ended</li>
</ul>

<p>&nbsp;</p>

<table>
    <tr>
        <th>Guest's Signature</th>
        <td class="signature_box">&nbsp;</td>

        <th>Date</th>
        <td class="signature_box">&nbsp;</td>
    </tr>
    <tr>
        <th>Support Worker's signature</th>
        <td class="signature_box">&nbsp;</td>

        <th>Date</th>
        <td class="signature_box">&nbsp;</td>
    </tr>
</table>

</div>

mediguest_reports/templates/mediguest_reports/client_pack/required_dynamic/M - Service Charge Sheet.html
<div class="document">

<h2>Service Charge Balance Sheet</h2>

<table class="bordered">
    <tr>
        <th>Guest Name:</th>            <td>{{ client }}</td>
        <th>Room No:</th>               <td>{% if client.room %}{{ client.room }}{% else %}(no room){% endif %}</td>
        <th>Booking-in Date:</th>
        <td>
            {% if client.room %}
                {{ client.booking_set.latest.start_date|date:"Y/M/d" }}
            {% else %}
                (no room yet)
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Date</th>
        <th>Receipt Number(s)</th>
        <th>Amount Paid</th>
        <th>Date paid up to and including night of</th>
        <th>SSW Name</th>
    </tr>
    {% for sc in client.service_charges.all %}
	    <tr>
	        <td>{{ sc.date_charged.date|date:"Y/M/d" }}</td>
	        <td>{% for payment in  sc.payments.all %}
                    {% if not forloop.first %}<br>{% endif %}
                    {{ payment.id }}
                {% endfor %}
            </td>
            <td>{{ sc.amount|floatformat:2 }}</td>
	        <td>{{ sc.last_payment_date|date:"Y/M/d" }}</td>
	        <td>{{ sc.authorizing_ssw }}</td>
	    </tr>
    {% endfor %}
</table>

</div>